on:
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setUpJava
        uses: actions/setup-java@v1
        with:
          node-version: 17

      - name: tests
        run: mvn test